image: golang:1.17

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_APPROVED
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - setup
  - build
  - lint
  - test

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
