image: golang:1.17

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - setup
  - build
  - lint
  - test

include:
  - local: .gitlab/ci/*.gitlab-ci.yml
